name: ci

on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: crisprime
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: |
            PRESTO_VERSION=0.273.2
          platforms: linux/amd64,linux/arm64
          tags: crisprime/zulu-openjdk:8-jre-headless
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"
